--
-- PostgreSQL database dump
--

\restrict 7xDUEFLwDOxWeaBppefvcZ01CgbjodGIQoE2o0sjWVNDUrBhVhfyEt9tuDM0YeI

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.news (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.news OWNER TO postgres;

--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message text,
    name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT requests_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'PROCESSED'::character varying])::text[])))
);


ALTER TABLE public.requests OWNER TO postgres;

--
-- Name: requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id bigint NOT NULL,
    description text,
    duration integer,
    price integer,
    title character varying(255) NOT NULL
);


ALTER TABLE public.services OWNER TO postgres;

--
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specialists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specialists (
    id bigint NOT NULL,
    description text,
    full_name character varying(255) NOT NULL,
    photo_url character varying(255),
    specialization character varying(255) NOT NULL
);


ALTER TABLE public.specialists OWNER TO postgres;

--
-- Name: specialists_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.specialists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specialists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.news (id, content, created_at, title) FROM stdin;
2	Центр ReHub подтвердил высокие стандарты качества и получил международный сертификат ISO 9001. Это гарантия прозрачности процессов и безопасности пациентов.	2025-11-16 03:00:00	Мы получили сертификат качества ISO 9001
3	Теперь доступны групповые занятия по управлению стрессом и эмоциональной устойчивости. Группы до 8 человек, занятия проводит клинический психолог.	2025-11-16 02:00:00	Запуск групповой психологической программы
4	В центр поступили современные аппараты для лазерной, магнитной и УВЧ-терапии. Новое оборудование позволяет ускорить восстановление в 1.5–2 раза.	2025-11-16 01:00:00	Поступило новое оборудование для физиотерапии
5	Центр ReHub расширяется — открылось новое отделение для работы с пациентами после инсульта и ЧМТ. Теперь доступны дополнительные кабинеты ЛФК, роботизированная механотерапия и VR-тренировки.	2025-11-16 00:00:00	Открыто новое отделение нейрореабилитации
\.


--
-- Data for Name: requests; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.requests (id, created_at, message, name, phone, status) FROM stdin;
35	2025-11-16 12:29:09.076864	помогите мне пожалуйста	иван	+791112223344	NEW
34	2025-11-16 12:28:22.556396	Помогите мне, пожалуйста	Дмитрий	+79998877766	PROCESSED
\.


--
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services (id, description, duration, price, title) FROM stdin;
1	Комплексное восстановление после инсульта, черепно-мозговых травм и неврологических нарушений. Включает ЛФК, эрготерапию, когнитивные тренировки и физиотерапию.	30	38000	Программа нейрореабилитации
2	Восстановление после инфаркта, операций на сердце и заболеваний сердечно-сосудистой системы. Укрепление организма, нормализация давления и пульса, подбор нагрузок.	21	27000	Кардиологическая реабилитация
3	Восстановление после переломов, операций на суставах, спортивных травм. Мануальная терапия, массажи, механотерапия, разработка суставов.	14	19500	Реабилитация после травм опорно-двигательного аппарата
4	Работа с тревожными состояниями, депрессией, хронической усталостью. Индивидуальные консультации, групповая терапия, техники релаксации.	10	12000	Психологическая и социальная реабилитация
\.


--
-- Data for Name: specialists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.specialists (id, description, full_name, photo_url, specialization) FROM stdin;
4	12 лет опыта работы. Специализируется на восстановлении после инсультов, ЧМТ и неврологических заболеваний. Автор программ нейродвигательной реабилитации.	Антонов Алексей Викторович	https://polisoms.ru/upload/iblock/bbb/gyyqvd2rzo9e696ipytyamq7qu71nliw.JPEG	Врач-реабилитолог
1	Помогает пациентам с тревожностью, эмоциональным выгоранием и нарушениями адаптации. Использует когнитивно-поведенческий подход.	Кузнецова Марина Андреевна	https://tokb.ru/upload/iblock/a01/eu6fn3rxsy64g69qd8qzkvda96y1knhb.webp	Клинический психолог
3	Проводит физиотерапевтические процедуры, использует современные методы лазерной и магнитотерапии. 9 лет практики.	Соколова Ирина Михайловна	https://orekhovo.clinic/wp-content/uploads/2019/11/qtq80-JPTuHY-min.jpeg	Физиотерапевт
2	Специалист по реабилитации после переломов, операций и спортивных травм. Работает с профессиональными спортсменами.	Кузнецов Тумба Юмба	https://cdnstatic.rg.ru/crop1240x828/uploads/images/2024/02/28/8p_doctor-1_4d5.jpg	Травматолог-ортопед
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, role, username) FROM stdin;
1	$2a$10$XUqjuRGO8x6DACzXR6eZxe3JPJOM/DtIp0ie8jiw82iLQATizc2dK	ADMIN	admin
\.


--
-- Name: news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.news_id_seq', 6, true);


--
-- Name: requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.requests_id_seq', 35, true);


--
-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_id_seq', 5, true);


--
-- Name: specialists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.specialists_id_seq', 5, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: specialists specialists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialists
    ADD CONSTRAINT specialists_pkey PRIMARY KEY (id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7xDUEFLwDOxWeaBppefvcZ01CgbjodGIQoE2o0sjWVNDUrBhVhfyEt9tuDM0YeI

